### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by RickysChocolateBox** [nicknochnack/TFODCourse#111]
after running "verification script"  I get
"Traceback (most recent call last):
  File "C:\Users\username\Desktop\Tensorflow Object Detection\TFODCourse\Tensorflow\models\research\object_detection\builders\model_builder_tf2_test.py", line 24, in <module>
    from object_detection.builders import model_builder
  File "C:\Users\username\anaconda3\lib\site-packages\object_detection\builders\model_builder.py", line 22, in <module>
    from object_detection.builders import box_predictor_builder
  File "C:\Users\username\anaconda3\lib\site-packages\object_detection\builders\box_predictor_builder.py", line 20, in <module>
    from object_detection.predictors import convolutional_box_predictor
  File "C:\Users\username\anaconda3\lib\site-packages\object_detection\predictors\convolutional_box_predictor.py", line 22, in <module>
    slim = tf.contrib.slim
AttributeError: module 'tensorflow' has no attribute 'contrib'"

**Comment by luongnguyentrong** [comment]
I'm facing the same issue, have you solved it ?

**Comment by luongnguyentrong** [comment]
Never mind, i have solved it, just manually delete the folder object_detection inside site_packages folder and run the command that uses protocol buffer again
