### ISSUE TITLE
VERIFICATION_SCRIPT Error

### ISSUE THREAD

**Issue by cjhsu1688** [nicknochnack/TFODCourse#25]
Run into the error messages as following:

Traceback (most recent call last):
  File "Tensorflow\models\research\object_detection\builders\model_builder_tf2_test.py", line 25, in <module>
    from object_detection.builders import model_builder
  File "C:\TFOD\TFODCourse\tfod\lib\site-packages\object_detection\builders\model_builder.py", line 20, in <module>
    from object_detection.builders import anchor_generator_builder
  File "C:\TFOD\TFODCourse\tfod\lib\site-packages\object_detection\builders\anchor_generator_builder.py", line 21, in <module>
    from object_detection.protos import anchor_generator_pb2
ImportError: cannot import name 'anchor_generator_pb2' from 'object_detection.protos' (C:\TFOD\TFODCourse\tfod\lib\site-packages\object_detection\protos\__init__.py)

Already searched solutions and tried without success. Please help, thanks.

**Comment by Suharda-Silva** [comment]
I solved most of the issues by uninstalling and reinstalling the dependencies. Maybe...?

**Comment by longqua69** [comment]
@cjhsu1688 Try restarting your kernel
