### ISSUE TITLE
I get the following error during training using python tensorflow\models\research\object_detection\model_main_tf2.py --model_dir=tensorflow\workspace\models\my_ssd_mobilenet --pipeline_config_path = tensorflow\workspace\models\my_ssd_mobilenet\pipeline.config --num_train_steps=2000

### ISSUE THREAD

**Issue by Shivam-21-11** [nicknochnack/TFODCourse#62]
`2022-02-28 13:00:27.096384: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2                                                                                           To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.                                                                               2022-02-28 13:00:27.642485: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 3991 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1660 Ti, pci bus id: 0000:01:00.0, compute capability: 7.5                                                                            INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)                                                                     I0228 13:00:27.767138  1196 mirrored_strategy.py:374] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)                               Traceback (most recent call last):                                                                                                                                          File "E:\MACHINELEARNING\TENSORFLOW_P\OBJD\tensorflow\models\research\object_detection\model_main_tf2.py", line 115, in <module>                                            tf.compat.v1.app.run()                                                                                                                                                  File "E:\MACHINELEARNING\TENSORFLOW_P\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 36, in run                                                      _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)                                                                                                    File "E:\MACHINELEARNING\TENSORFLOW_P\tensorflow\lib\site-packages\absl\app.py", line 312, in run                                                                           _run_main(main, args)                                                                                                                                                   File "E:\MACHINELEARNING\TENSORFLOW_P\tensorflow\lib\site-packages\absl\app.py", line 258, in _run_main                                                                     sys.exit(main(argv))                                                                                                                                                    File "E:\MACHINELEARNING\TENSORFLOW_P\OBJD\tensorflow\models\research\object_detection\model_main_tf2.py", line 106, in main                                                model_lib_v2.train_loop(                                                                                                                                                File "E:\MACHINELEARNING\TENSORFLOW_P\tensorflow\lib\site-packages\object_detection-0.1-py3.9.egg\object_detection\model_lib_v2.py", line 504, in train_loop                configs = get_configs_from_pipeline_file(                                                                                                                               File "E:\MACHINELEARNING\TENSORFLOW_P\tensorflow\lib\site-packages\object_detection-0.1-py3.9.egg\object_detection\utils\config_util.py", line 138, in get_configs_from_pipeline_file                                                                                                                                                                 proto_str = f.read()                                                                                                                                                    File "E:\MACHINELEARNING\TENSORFLOW_P\tensorflow\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 114, in read                                                  self._preread_check()                                                                                                                                                   File "E:\MACHINELEARNING\TENSORFLOW_P\tensorflow\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 76, in _preread_check                                         self._read_buf = _pywrap_file_io.BufferedInputStream(                                                                                                                 tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: = : The system cannot find the file specified.                          ; No such file or directory  `

**Comment by Shivam-21-11** [comment]
I fixed it just by removing the whitespace from both side of = `--pipeline_config_path = tensorflow\workspace\models\my_ssd_mobilenet\pipeline.config`.

`--pipeline_config_path=tensorflow\workspace\models\my_ssd_mobilenet\pipeline.config` this fixed it
