### ISSUE TITLE
keyerror : 'licence' in step 3 creating tf records

### ISSUE THREAD

**Issue by Abhishekpotpally** [nicknochnack/TFODCourse#85]
I am getting this issue will creating tf records

Traceback (most recent call last):
  File "D:\ANPR\Tensorflow\scripts\generate_tfrecord.py", line 168, in <module>
    tf.app.run()
  File "D:\ANPR\anprsys\lib\site-packages\tensorflow\python\platform\app.py", line 36, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "D:\ANPR\anprsys\lib\site-packages\absl\app.py", line 312, in run
    _run_main(main, args)
  File "D:\ANPR\anprsys\lib\site-packages\absl\app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "D:\ANPR\Tensorflow\scripts\generate_tfrecord.py", line 158, in main
    tf_example = create_tf_example(group, path)
  File "D:\ANPR\Tensorflow\scripts\generate_tfrecord.py", line 132, in create_tf_example
    classes.append(class_text_to_int(row['class']))
  File "D:\ANPR\Tensorflow\scripts\generate_tfrecord.py", line 101, in class_text_to_int
    return label_map_dict[row_label]
KeyError: 'licence'
Traceback (most recent call last):
  File "D:\ANPR\Tensorflow\scripts\generate_tfrecord.py", line 168, in <module>
    tf.app.run()
  File "D:\ANPR\anprsys\lib\site-packages\tensorflow\python\platform\app.py", line 36, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "D:\ANPR\anprsys\lib\site-packages\absl\app.py", line 312, in run
    _run_main(main, args)
  File "D:\ANPR\anprsys\lib\site-packages\absl\app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "D:\ANPR\Tensorflow\scripts\generate_tfrecord.py", line 158, in main
    tf_example = create_tf_example(group, path)
  File "D:\ANPR\Tensorflow\scripts\generate_tfrecord.py", line 132, in create_tf_example
    classes.append(class_text_to_int(row['class']))
  File "D:\ANPR\Tensorflow\scripts\generate_tfrecord.py", line 101, in class_text_to_int
    return label_map_dict[row_label]
KeyError: 'licence'

**Comment by snakebit18** [comment]
same problem have you found the solution

**Comment by aksripu** [comment]
i am also having same problem please help

**Comment by davemaster** [comment]
See the video again, in the tfrecord part....

**Comment by aksripu** [comment]
i tried but still i did not get it

**Comment by davemaster** [comment]
I remember, the tfrecord is included in the git file. You have to EDIT that tfrecord.py file to fit the licence unique class
