### ISSUE TITLE
 VERIFICATION_SCRIPT = os.path.join(paths['APIMODEL_PATH'], 'research', 'object_detection', 'builders', 'model_builder_tf2_test.py') # Verify Installation !python {VERIFICATION_SCRIPT}

### ISSUE THREAD

**Issue by deb-cod** [nicknochnack/TFODCourse#92]
2022-06-01 19:34:30.543360: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-06-01 19:34:30.543474: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "E:\Fire_Detection\prime_folder\Tensorflow\models\research\object_detection\builders\model_builder_tf2_test.py", line 24, in <module>
    from object_detection.builders import model_builder
  File "E:\Fire_Detection\prime_folder\Fire\lib\site-packages\object_detection-0.1-py3.9.egg\object_detection\builders\model_builder.py", line 23, in <module>
    from object_detection.builders import anchor_generator_builder
  File "E:\Fire_Detection\prime_folder\Fire\lib\site-packages\object_detection-0.1-py3.9.egg\object_detection\builders\anchor_generator_builder.py", line 26, in <module>
    from object_detection.protos import anchor_generator_pb2
  File "E:\Fire_Detection\prime_folder\Fire\lib\site-packages\object_detection-0.1-py3.9.egg\object_detection\protos\anchor_generator_pb2.py", line 15, in <module>
    from object_detection.protos import flexible_grid_anchor_generator_pb2 as object__detection_dot_protos_dot_flexible__grid__anchor__generator__pb2
  File "E:\Fire_Detection\prime_folder\Fire\lib\site-packages\object_detection-0.1-py3.9.egg\object_detection\protos\flexible_grid_anchor_generator_pb2.py", line 21, in <module>
    _FLEXIBLEGRIDANCHORGENERATOR = DESCRIPTOR.message_types_by_name['FlexibleGridAnchorGenerator']
AttributeError: 'NoneType' object has no attribute 'message_types_by_name'

**Comment by deb-cod** [comment]
plzz.. help

**Comment by mipranjal** [comment]
hi
you need to  Install CUDA and cuDNN according to your tensorflow version as mentioned in the video
